// Automatically generated by MockGen. DO NOT EDIT!
// Source: api.go

package mediawiki

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *_MockClientRecorder
}

// Recorder for MockClient (not exported)
type _MockClientRecorder struct {
	mock *MockClient
}

func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &_MockClientRecorder{mock}
	return mock
}

func (_m *MockClient) EXPECT() *_MockClientRecorder {
	return _m.recorder
}

func (_m *MockClient) Login() error {
	ret := _m.ctrl.Call(_m, "Login")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockClientRecorder) Login() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Login")
}

func (_m *MockClient) ListArticleTitles() ([]string, error) {
	ret := _m.ctrl.Call(_m, "ListArticleTitles")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockClientRecorder) ListArticleTitles() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListArticleTitles")
}

func (_m *MockClient) GetArticle(title string) (string, error) {
	ret := _m.ctrl.Call(_m, "GetArticle", title)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockClientRecorder) GetArticle(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetArticle", arg0)
}
